spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:16349/railway?useSSL=true&requireSSL=true
spring.datasource.username=root
spring.datasource.password=syYefmtFplpBiDSQnYIKFBDkZUwjKdoJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true